### ISSUE TITLE
Could you please tell me how you draw this?

### ISSUE THREAD

**Issue by lnnt** [sagpant/swiftshader#1]
https://github.com/sagpant/swiftshader/blob/9167e1e22a46da914dd134c00f7f11cac0e2548f/tests/regres/cov/coverage_test.go#L37-L45
Thank you very much!
@ben-clayton

**Comment by ben-clayton** [comment]
I'd love to say I have some secret drawing software, but I go to https://en.m.wikipedia.org/wiki/Box-drawing_character, copy out the unicode symbols I need, and make heavy use of multi-caret insertion and deletion in VSCode.
It takes time, but I feel inline charts are better than the alternatives. :)
